### ISSUE TITLE
Spec 1 block finality

### ISSUE THREAD

**Issue by carterqw2** [celo-org/optimism#103]

**Comment by palango** [comment]
I created the following document to specify our changes to OP for 1-block finality: https://www.notion.so/clabsco/1-block-finality-0b7efa6b2c0a41909cd2a8f84947c011

TLDR:
- This is about avoiding reorgs based on Ethereum reorgs. It's implemented by using only finalized Ethereum blocks as l1 origin blocks. Sideffects are slower deposits and withdrawals.
- This proposal does not solve the problem of fault-proof induced reorgs. As we (initially) run the sequencer, this should not be a problem, but people will point this out. [maybe we should name this differently?]
- There's some unknowns around EigenDA and the DA challenge mechanism. The contract for challenges does not exist yet and it's unclear how challenging windows and sequencing windows would interact.
