### ISSUE TITLE
Write a tool that checks the migrated state

### ISSUE THREAD

**Issue by carterqw2** [celo-org/optimism#109]
### Tasks
- https://github.com/celo-org/optimism/issues/196
- https://github.com/celo-org/optimism/issues/197

**Comment by piersy** [comment]
Somewhat unclear what to do here. With good testing we should be able to verify that the migration is good.

Simply checking that contracts are in the right place is something that can be enforced during migration, writing a test for it would likely duplicate code/logic.

**Comment by piersy** [comment]
Can add a step to the migration guide to check migration block is correct.

**Comment by piersy** [comment]
Should we audit the migration script?

**Comment by piersy** [comment]
Potentially a post migration smoke test to just check that things are not way off

**Comment by lvpeschke** [comment]
Moved into https://github.com/celo-org/celo-blockchain-planning/issues/387.
