### ISSUE TITLE
Decide behaviour when overwriting state during migration

### ISSUE THREAD

**Issue by palango** [celo-org/optimism#173]
When a collition happens during copying the L2 contracts into the state we currently overwrite the existing state.
https://github.com/celo-org/optimism/blob/b5a2af7f414a2359a2925946c1a03f8aa88c4f9b/op-chain-ops/cmd/celo-migrate/state.go#L266

This might not be what we want to do during mainnet migration though. Alternative options include stopping the migration when this happens or logging a warning (although this risks a broken state after migration).

**Comment by mcortesi** [comment]
@palango Can you expando on what this is? The problem? context, etc?

**Comment by piersy** [comment]
We decided, @mcortesi said we fail and if we fail then there needs to be some manual intervention to resolve the failure.

Since we will test migration before the real thing it is unlikely that we will encounter any failures during the real migration.

**Comment by piersy** [comment]
I closed this prematurely, even though we have decided the behaviour we now need to implement this decision.

**Comment by lvpeschke** [comment]
@palango should "Elapsed + remaining (hours)" be updated to 5? Is that number final?
