### ISSUE TITLE
Check setup of hardforks (e.g. Ecotone requires a contract deployment)

### ISSUE THREAD

**Issue by lvpeschke** [celo-org/optimism#197]
```[tasklist]
### Tasks
- [ ] Check that required contracts get deployed and initialized
- [ ] Check that required upgrade transactions are executed
```

**Comment by palango** [comment]
Might get more difficult after https://github.com/celo-org/celo-blockchain-planning/issues/350

**Comment by palango** [comment]
Some code in question:
https://github.com/celo-org/optimism/blob/cb53122a2bf2a04f7d17bdeefe881b0faaada8e5/op-node/rollup/derive/attributes.go#L103-L140

**Comment by palango** [comment]
With the approach in https://github.com/celo-org/optimism/pull/212 there won't be any upgrade transactions run.
Everything required is done during the creation of the allocation file.

Remaining questions about contract deployments are tracked in https://github.com/celo-org/celo-blockchain-planning/issues/551#issuecomment-2306790761
