### ISSUE TITLE
Update the migration script documentation

### ISSUE THREAD

**Issue by piersy** [celo-org/optimism#203]
There should be a migration guide in the docs.

Then there is the readme for the migration tool, so should be up to date and explain correctly how the tool works.

We probably want to add instructions for using docker and potentially a helm chart.

Also we will need to update the instructions when we update the migration script to allow migrating at a specific block.

**Comment by lvpeschke** [comment]
@piersy @alecps @palango 
The canonical node migration guide is at https://docs.celo.org/cel2/l2-operator-guide.
What's missing to call it up to date?

**Comment by alecps** [comment]
Synced with @lvpeschke and it seems we should probably update the scope of this ticket or close (pending further investigation). There's some semantic blurriness here with the task of updating the cel1 -> cel2 operator guide, which has a much broader scope than just documenting the migration script

**Comment by lvpeschke** [comment]
@alecps I think the confusion initially stems from de-duping this issue and https://github.com/celo-org/celo-blockchain-planning/issues/374, which had the broader scope.
