### ISSUE TITLE
Create PR-bot to update op-geth versions (docker / go.mod)

### ISSUE THREAD

**Issue by ezdac** [celo-org/optimism#262]
Currently the docker base container for building the `l2` node (op-geth) in the local devnet has 
to be [manually updated](https://github.com/celo-org/optimism/commit/352179dc52e942ed2a4ea44a84fa3f6a4ebd5ac1#diff-065d58e728b4f3cad51b8234f75a1bb96c1cbe0d40de89bcb49308cfce17d1a7R1).

For this, the correct sha256 digest from the image at [blockchaintestsglobaltestnet/us-west1/dev-images/op-geth/](https://console.cloud.google.com/artifacts/docker/blockchaintestsglobaltestnet/us-west1/dev-images/op-geth/) tagged with the most recent default branch commit has to be found.

Additionally the go dependency should reflect the same version of `op-geth` in the go.mod file's replace directive.

It would be good to update this regularly, especially as soon as we do more testing of Celo specific STF features in the optimsim e2e suite.
This could be achieved by a Github action that [opens a pull-request ](https://github.com/marketplace/actions/create-pull-request) with `sed`ing the `go.mod` and Docker files.

**Comment by palango** [comment]
Closed in https://github.com/celo-org/optimism/pull/263
