### ISSUE TITLE
Which Celo core contracts do we need on Cel2?

### ISSUE THREAD

**Issue by karlb** [celo-org/optimism#5]
Go through Celo core contracts and put each contract in one of these groups:
* Not needed anymore
* Can be used unchanged
* Needs modification

Also list the precompiles needed by each contract that is kept.

It could also be helpful to categorize contracts as
* Needed for geth
* Needed for the validators/decentralized sequencer
* "Normal" contract (e.g. for identity)

**Comment by palango** [comment]
We'll need an fee currency compatible token in #56 and the whitelist contract in #57 .

**Comment by pahor167** [comment]
I created following document (feel free to update) https://docs.google.com/spreadsheets/d/1LAfpy5S1Iekw5zX46LhS12_2z218cIzqQYdItHuFgJk/edit?usp=sharing

**Comment by karlb** [comment]
The sheet describes the current situation well, so I'll close this issue.
