### ISSUE TITLE
Adjust receipts APIs

### ISSUE THREAD

**Issue by palango** [celo-org/optimism#61]
Subtask of #6 

When receipts for a celo transaction a re requested that is included in an block which has it's state pruned (currently after 128 blocks) we cannot access the basegasprice from the contract state any more.

In that case the fields of the receipt should be empty.

- Adjust `core/types/receipt.go`, `Receipts.EncodeIndex` to handle celo transactions as well
- Add tests for this and make sure common client libraries can handle this.

**Comment by karlb** [comment]
The current suggestion (from https://www.notion.so/clabsco/ERC20-fee-currencies-for-CEL2-7fbf7c53e52c4cacab6e8e61d290fe93?d=166941fb65644bc9a2d7eefaf619dd6d#4084eb863a0e48358d8715d34d656b36) is to store an `effectiveGasPrice` in the receipt (not only generate in upon request) to keep the information available even after the state has been pruned.
