### ISSUE TITLE
Evaluate usage of the L1Cost fn in the txpool for filtering txs

### ISSUE THREAD

**Issue by hbandura** [celo-org/optimism#99]
Upstream uses the function L1CostFn on txs' calldata to evaluate the l1 cost of a tx. However it does not seem to track it properly, e.g it's added to the totalcost but not removed when the tx is removed.

Understand how it should be implemented., if it's constant or not, and fix upstream's mistake (if any).
If current implementation is actually ok, re-add the commented parts (double check for mistakes during different refactors on implementation of fee currency txpool)

**Comment by lvpeschke** [comment]
@celo-org/blockchain can you link this to an epic?

**Comment by karlb** [comment]
The known issues are fixed in https://github.com/celo-org/op-geth/pull/183.
